server:
  servlet:
    context-path: /dpe-app-ms-user
##CONFIGURE DATASOURCE MYSQL
spring:
  datasource:
    url: jdbc:mysql://localhost/syscoma?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

# Naming strategy
  jpa:
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
eureka:
  client:
    enabled: false
    #service-url: http://192.168.0.5:9007/dpe-app-ms-eurekaserver/